### ISSUE TITLE
find block without variable name in the title

### ISSUE THREAD

**Issue by rxie25** [rxie25/PLT2016Spring#45]
we need to add syntax for find block that doesn't take a variable ID.
```
SomeContext = {
}

SomeContext:find {
  print("Hello World\n");
}
```

**Comment by jzacsh** [comment]
Not worth fixing for "hello world" submission. Will require grammar updates and semantic analysis to verify the contents inside the `find` block are all truly resolved

**Comment by rxie25** [comment]
we are only changing the grammar slightly so that out language accepts a program with no variable id after find.

**Comment by jzacsh** [comment]
Mm.. right now? I don't think we need/should work on this (or anything outside of the Hello World milestone), since we have a lot more important codegen and semantic analysis work to do and due in like 5 days _(and only one big group meeting before then)_
