### ISSUE TITLE
scanner/parser: consider global equations

### ISSUE THREAD

**Issue by jzacsh** [rxie25/PLT2016Spring#6]
In our LRM we allow global equations (and as such, `find` blocks that have no context-prefix).

TODO for the team: decide if we care about this. if:
- **we care**: implement it in scanner/parser
- **don't care**: throw it out of our LRM[1]

[1]: this means throw out any other complexities like, TODOs left behind in the scanner parser that would go way (eg: optional Context prefixes, etc.)

**Comment by jzacsh** [comment]
here's a reference to the exact TODO that this issue is tracking: https://github.com/rxie25/PLT2016Spring/blob/51f275435349af438020d95a3c23f7c1739747e2/src/parser.mly#L41-L45

**Comment by jzacsh** [comment]
Note: this is the lowest priority bug. We can complete our grammar and our "hello world" without blocking on this detail

**Comment by rxie25** [comment]
#85

**Comment by jzacsh** [comment]
fixed in #85
