### ISSUE TITLE
issues and discrepencies between LRM & our code

### ISSUE THREAD

**Issue by rxie25** [rxie25/PLT2016Spring#62]
This is a list of discrepancies we have between the current language and the LRM. We either have to add or modify features in our language or revise the LRM. A lot of them deserve to be their own issues. Most of the stuff on the list is not that hard. So feel free to take on the tasks, just make sure you link your issue to this list.

- [x] ~~issue #6~~ & #94: Number of context blocks.

  In the LRM we have our language can accept 'zero or more "context" blocks' . However, currently in
  our language the find block requires cxt. With zero context block it will raise 
  ```
  Fatal error: exception Failure("unrecognized context, "SomeContext"")
  ```
  with no context before find it will raise
  ```
  Fatal error: exception Failure("unrecognized context, """)
  ```
- [x] issue #4:
  - ["Tokens: Expressions' Lexemes"](https://github.com/rxie25/PLT2016Spring/blob/master/notes/language-reference-manual.md#tokens-expressions-lexemes) section
  - change sample code in our LRM
    - capitalize scope name 
    - change comment style
    - settle on "requisite" `=` following context name's in declarations _(ie: either add to LRM or fix
    our grammar)_
- [x] issue #63 
    - Multi-line equations not implemented 
- [x] This is probably not that important maybe we want to proper indention for our c output so
  it's more readable. But it doesn't really affect the correctness of our language, so I think we can
  deal with it later.
- [x] issue #85 
Global scope not implemented.
```
VAR = EXPR

Scope_name {
  list of equations
  // VAR = EXPR // overwrites global `VAR`
}

Scope_name: find VAR [with VAR_B in range()]* ] {
  /** code here has access to `Scope_name`'s equations */
}
```
- [x] Confused about Expression Statement under section Statement.
Expression statements are statement that includes an expression and a semicolon at the end:
``` 
expression ;
```
- [x] issue #79 
`return` semantic analysis
- [x] Make sure `if`, `else`, `while`, `break`, and `continue` are all implemented and works as they are specified in the LRM.(create tests, fix bugs, add to the compiler)
    - [x] issue #66 @kekeleila `break`, `continue`
    - [x]  `else if` implement
- [x] issue #38 #69 
    - Implement `with` , `in`, and `range`. 
- [x] issue #64 
    - Test all operator expression examples in the expression section of LRM. Modify test-arithmetic-basic.eq to test the following @tiancizhong will work on this. 
    - `>`, `<`, `!=`, `==`, `<=`, `>=`, `!=`, `||`, `&&`, `+`, `-`, `*`, `\`
    - operators already tested `=`, `%`, `| |`, `^`
- [x] Note in LRM on how rounding works for our language int/int is round to the nearest int. For example 3/2 = 2 instead of 3/2 =1 like in C because 1.5 is round to 2 in our language.

- [x] Make sure gcd.eq is correctly implemented 
- [x] Make sure pendulum.eq is correctly implemented

---

**Comment by jzacsh** [comment]
awesome stuff, Jimmy! Thanks for writing this up. Edits I made:
1. added links to existing issues
2. fixed markdown to it shows as a list throughout
3. removed the C input/output for "multi-line equations not implemented" because I think that is just confusion I've caused: I originally started the compiler off with the multi-line **syntax** just because it was easier _(in the grammar)_ at the time, but we have definitely made **zero** attempts to actually implement multi-line yet.

**Comment by rxie25** [comment]
So for the milestones. I think there are three important programs we need to make sure it works properly, hello world, gcd, and resolving equations. While @jzacsh  and @nnhoang working on creating dependency tables and reducing equations. @tiancizhong (because you figured out how to create separate function for find block, you have a good understanding of how to do similar things to multi-equations) and I can work on the gcd. Once all three examples works in our language, we should be on track with our project.

**Comment by jzacsh** [comment]
@rxie25 do you think multi-line equations are necessary for Hello World? I'm thinking maybe our HelloWorld demo is good for now. What do you think? Anyway, up to you, just wanted to file #63 under the correct milestone

**Comment by rxie25** [comment]
Yeah, you are right. We don't need it for hello world. Maybe you can create a new milestone GCD, as there are probably a number of features we need to implemnt to make the GCD example work.

**Comment by jzacsh** [comment]
@rxie25 is this completed now?

**Comment by rxie25** [comment]
No, they related to LRM, we can do it after our presentation tomorrow.
