### ISSUE TITLE
grammar: expand "context" to capture single-line equations as well

### ISSUE THREAD

**Issue by jzacsh** [rxie25/PLT2016Spring#7]
currently our grammar doesn't address simple single-line equations, eg [`ctxdecl` in parser.mly](https://github.com/jzacsh/PLT2016Spring/commit/51f275435349af438020d95a3c23f7c1739747e2#diff-c66abaa9490e32889b002b674c0573cdR49)

this is probably some simple finagling of the grammar to make something more restrictive than a normal `expr` as we inherited them from microc.

**Comment by rxie25** [comment]
It's done in #63
