### ISSUE TITLE
e2e vector support

### ISSUE THREAD

**Issue by jzacsh** [rxie25/PLT2016Spring#73]
bullet 3 under ["Declarations" in LRM](https://github.com/rxie25/PLT2016Spring/blob/master/notes/language-reference-manual.md#declarations)

**Comment by rxie25** [comment]
@kekeleila is currently working on this.

**Comment by rxie25** [comment]
@jzacsh We probably wont have time for this. Since it's not essential to our language. I will just close it.

**Comment by jzacsh** [comment]
mind updating our LRM to remove everything about vectors? by the way, do we have a mid-progress pull request somewhere and get stuck, or just never started?
