### ISSUE TITLE
fix scanner/parser of IF/ELSEIF/ELSE

### ISSUE THREAD

**Issue by jzacsh** [rxie25/PLT2016Spring#77]
currently it isn't [clear if we've thought carefully in our parsing](https://github.com/rxie25/PLT2016Spring/blob/d58408f98a2541d53c105d5cbaf948aa0bfd1efe/src/parser.mly#L117) about user inputs:
```c
if (a) {
  //...
} else {
  // ...
} else if (b) {
  //...
}
```

maybe we can just use this issue to:
1. add a bunch of tests for funky things we want to disallow
2. then figure out if we need real changes to the scanner/parser

**Comment by rxie25** [comment]
Sure, I can add some fail tests for the if, else if statement.

**Comment by rxie25** [comment]
C takes string as legal argument for if and else if condition. So does our language.  I don't know if we want to do that for a math language.
We also may want to catch `print` and `assignment` as if else if conditions, which is also legal both in C and our language.

**Comment by jzacsh** [comment]
> C takes strings as legal argument

No, I don't think we want our language to accept such predicates

> We also may want to catch `print` and `assignment` as if else if conditions

Sounds good, I think we should indeed catch that _(or `Ast.Builtin`s being used as predicates, at least)_
