### ISSUE TITLE
generate final report

### ISSUE THREAD

**Issue by jzacsh** [rxie25/PLT2016Spring#95]
So Nam can compile our report, please:
 1. check your box when you've committed your section in `notes/report/*.md` eg: _"LRM"_ below....
 2. use only `## header{2,3,4,5,6}` heading-levels in your file section

- [x] Intro @kekeleila
- [x] Tutorial @tiancizhong 
- [x] LRM @jzacsh de77237e4d70d
- [x] Project Plan @rxie25 
- [x] Compiler Architecture @nnhoang 
- [x] Test Coverage @jzacsh - 346d251e1b6e7582d73
- [x] Lessons Learned
  - [x] @nnhoang 
  - [x] @rxie25 
  - [x] @kekeleila 
  - [x] @tiancizhong 
  - [x] @jzacsh
- [x] Conclusions @kekeleila 
- [x] Full Code Listing @nnhoang
    `Makefile`, `ast.ml`, `scanner.mll`, `parser.mly`, `sast.ml`, `semant.ml`, `codegen.ml`, `eqeq.ml`

- [x] final report: @nnhoang - actually generate[1] the final report itself, once everything above is done

---
taken directly from @nnhoang outline of responsibilities in fbb6e79672468a9511

[1]: in case it helps, you can see how I generated the LRM in [`notes/lrm-to-pdf.sh`](https://github.com/rxie25/PLT2016Spring/blob/master/notes/lrm-to-pdf.sh)

**Comment by jzacsh** [comment]
@rxie25 @tiancizhong @kekeleila just a heads up about this - I'm guessing nam will need this by tonight or early tomorrow _(he'll need time to put everything together into a single PDF)_

**Comment by jzacsh** [comment]
@kekeleila fyi i unchecked your box for "conclusions" because i dont' see any new commits on `master`. feel free to recheck _(just maybe add your commit hash so it is easier to verify it is really done)_

**Comment by nnhoang** [comment]
@jzacsh everyone else is writing to `notes/final-report.md`... I think I'll compile from that file then

**Comment by jzacsh** [comment]
@nnhoang you're the one compiling - whatever you want :) _(you know where my bits are)_
