### ISSUE TITLE
equation graph should allow recursive calls per LRM

### ISSUE THREAD

**Issue by jzacsh** [rxie25/PLT2016Spring#96]
per our LRM, there is *one* specific case where an equation can look like it depends on itself: IFF it is the return value (ie: it is a statement that is itself just a single expression). eg:

```sh
gcd = {
  // ...
  gcd; // recursively call self
}
```

## Solution
This is probably trivial to fix if anyone wants to take it on. The edge-case _(that we want to allow a cyclical dependency)_ needs to be added for consideration that

The [`R.exprRelator`][exprel] should have some notion it passes around (currently passes a tuple of two items, so this would mean adding a third item) as to whether or not it is looking at an expression *inside* an expression (ie: a **recursive** call to `exprRelator`). This would allow us to know if [`A.id(...)` match][id] is OK to be cyclical

Note that the `gcd = {...}` high-level analysis is not done by the usual [`R.exprRelator`'s `A.Assign` matcher][exprel], but is called from the outside, and [**only provided** the `A.multi_eq` body, here][multi_eqbody]

[exprel]: https://github.com/rxie25/PLT2016Spring/blob/346d251e1b6e7582d73e8c7172a1a1a75062dfac/src/relation.ml#L90-99
[id]: https://github.com/rxie25/PLT2016Spring/blob/346d251e1b6e7582d73e8c7172a1a1a75062dfac/src/relation.ml#L85
[multi_eqbody]: https://github.com/rxie25/PLT2016Spring/blob/346d251e1b6e7582d73e8c7172a1a1a75062dfac/src/relation.ml#L146

**Comment by jzacsh** [comment]
@rxie25 feel free to tackle this if you want. otherwise, just unassign it from yourself :)

**Comment by rxie25** [comment]
I can take a try at it.

**Comment by rxie25** [comment]
well I tried, it seems to be harder than it looks. sorry.

**Comment by rxie25** [comment]
so I tried to add the multi-equation name to the two elements tuple, so when the `expr.ID matches multi-equation name` it doesn't report a dependency problem, but I have to pass it to the functions that wraps a round it, like `stLiRelator`, and there are `u`, `m`, `acc`, and `accum` and whole bunch of other stuff that I have no idea what they are.

**Comment by jzacsh** [comment]
fixed by db91716
